# Generated by Django 4.0 on 2022-03-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
