# Generated by Django 4.0 on 2022-03-21 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0017_comment_users_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='users_liked',
            field=models.ManyToManyField(related_name='articles_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
